import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import SessionWrapper from "./sessionWrapper";
import { ThemeProvider } from "@/components/theme-provider";
const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "PhysiClub for Great teaching",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${jakarta.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <SessionWrapper>
            {children}
            <Toaster richColors position="bottom-center" expand={true} />
          </SessionWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
