import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import SessionWrapper from "./sessionWrapper";
const outfit= Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "PhysiClub for Great teaching",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${outfit.variable} antialiased`}
      >
        <SessionWrapper>

        {children}
        <Toaster richColors  position="bottom-center" expand={true} />
        </SessionWrapper>
      </body>
    </html>
  );
}
